name: Build & Deploy
on:
	push:
		branches: [main]

jobs:
	deploy:
		runs-on: ubuntu-latest
		steps:
			- name: Deploy Brimbot
				uses: appleboy/ssh-action@v0.1.2
				with:
					host: ${{ secrets.SSH_HOST }}
					key: ${{ secrets.SSH_KEY }}
					username: ${{ secrets.SSH_USERNAME }}

					script: |
						rm -r brimbot
						mkdir brimbot
						cd brimbot
						git clone git@github.com:TheFunkyMonk/brimbot.git .
						npm install
						forever restart 0
						echo "Deployment successful to DigitalOcean"
